# Generated by Django 6.1.1 on 2026-10-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0002_gamesession_participant_settingsversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_centavos", models.BigIntegerField()),
                ("chips", models.BigIntegerField()),
                ("request_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buy_ins",
                        to="games.participant",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buy_ins",
                        to="games.gamesession",
                    ),
                ),
                (
                    "settings_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="games.settingsversion",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="BuyInReversal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buy_in",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="ledger.buyin",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="buyin",
            index=models.Index(fields=["participant"], name="buy_in_participant"),
        ),
        migrations.AddConstraint(
            model_name="buyin",
            constraint=models.UniqueConstraint(
                fields=("session", "request_id"), name="buy_in_request_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="buyin",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_centavos__gt", 0)),
                name="buy_in_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="buyin",
            constraint=models.CheckConstraint(
                condition=models.Q(("chips__gt", 0)), name="buy_in_chips_positive"
            ),
        ),
    ]
