# Generated by Django 6.1.1 on 2026-10-03 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_gamesession_participant_settingsversion_and_more"),
        (
            "ledger",
            "0002_cashout_cashoutreversal_cashout_cash_out_participant_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chips_delta", models.BigIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("player", "One named player"),
                            ("equal", "Shared equally"),
                        ],
                        max_length=8,
                    ),
                ),
                ("note", models.CharField(max_length=255)),
                ("request_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="games.participant",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="games.gamesession",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["session"], name="adjustment_session")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "request_id", "participant"),
                        name="adjustment_request_once",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("chips_delta", 0), _negated=True),
                        name="adjustment_not_zero",
                    ),
                ],
            },
        ),
    ]
