# Generated by Django 6.1.1 on 2026-10-03 14:54

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_gamesession_participant_settingsversion_and_more"),
        ("groups", "0002_invite"),
        ("ledger", "0003_balanceadjustment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=True)),
                ("total_buy_in_centavos", models.BigIntegerField()),
                ("total_cash_out_centavos", models.BigIntegerField()),
                ("chips_issued", models.BigIntegerField()),
                ("raw_difference_chips", models.BigIntegerField(default=0)),
                ("rate_centavos", models.BigIntegerField()),
                ("rate_chips", models.BigIntegerField()),
                ("settings_snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finalizations",
                        to="games.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "revision"],
            },
        ),
        migrations.CreateModel(
            name="PlayerResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_date", models.DateField()),
                ("buy_in_total_centavos", models.BigIntegerField()),
                ("buy_in_count", models.PositiveIntegerField()),
                ("chips_cashed", models.BigIntegerField()),
                ("adjustment_chips", models.BigIntegerField(default=0)),
                ("cash_out_centavos", models.BigIntegerField()),
                ("net_centavos", models.BigIntegerField()),
                ("is_current", models.BooleanField(default=True)),
                (
                    "finalization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="ledger.finalization",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="groups.gamegroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="groups.member",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="games.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["finalization", "participant__join_order"],
            },
        ),
        migrations.AddConstraint(
            model_name="finalization",
            constraint=models.UniqueConstraint(
                fields=("session", "revision"), name="finalization_revision_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="finalization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("session",),
                name="finalization_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="finalization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_buy_in_centavos", models.F("total_cash_out_centavos"))
                ),
                name="finalization_money_conserved",
            ),
        ),
        migrations.AddIndex(
            model_name="playerresult",
            index=models.Index(
                condition=models.Q(("is_current", True)),
                fields=["member", "game_date"],
                name="result_member_date",
            ),
        ),
        migrations.AddIndex(
            model_name="playerresult",
            index=models.Index(
                condition=models.Q(("is_current", True)),
                fields=["group", "game_date"],
                name="result_group_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerresult",
            constraint=models.UniqueConstraint(
                fields=("finalization", "participant"),
                name="result_once_per_finalization",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("participant",),
                name="result_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "net_centavos",
                        django.db.models.expressions.CombinedExpression(
                            models.F("cash_out_centavos"),
                            "-",
                            models.F("buy_in_total_centavos"),
                        ),
                    )
                ),
                name="result_net_is_cash_out_minus_buy_ins",
            ),
        ),
    ]
