# Generated by Django 6.1.1 on 2026-10-03 15:19

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_gamesession_state_and_more"),
        ("groups", "0002_invite"),
        ("ledger", "0005_amounts_instead_of_chips"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="balanceadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="adjustment_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="buyin",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="buy_in_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashout",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="cash_out_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="finalization",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_buy_in", models.F("total_cash_out"))),
                name="finalization_money_conserved",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "net",
                        django.db.models.expressions.CombinedExpression(
                            models.F("cash_out"), "-", models.F("buy_in_total")
                        ),
                    )
                ),
                name="result_net_is_cash_out_minus_buy_ins",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "cash_out",
                        django.db.models.expressions.CombinedExpression(
                            models.F("cashed_out"), "+", models.F("adjustment")
                        ),
                    )
                ),
                name="result_cash_out_includes_adjustment",
            ),
        ),
    ]
