# Generated by Django 6.1.1 on 2026-10-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_backfill_ended_at"),
        ("ledger", "0006_balanceadjustment_adjustment_not_zero_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashout",
            name="kind",
            field=models.CharField(
                choices=[("partial", "Partial"), ("final", "Final")],
                default="final",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="FinalCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                ("request_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_counts",
                        to="games.participant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_counts",
                        to="games.gamesession",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="cashout",
            name="final_count",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_out",
                to="ledger.finalcount",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashout",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["partial", "final"])),
                name="cash_out_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="finalcount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("participant",),
                name="final_count_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="finalcount",
            constraint=models.UniqueConstraint(
                fields=("participant", "version"), name="final_count_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="finalcount",
            constraint=models.UniqueConstraint(
                fields=("session", "request_id"), name="final_count_request_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="finalcount",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="final_count_not_negative"
            ),
        ),
    ]
