# Generated by Django 6.1.1 on 2026-10-04 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_grouprakeaccount"),
        ("ledger", "0010_playerresult_play_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="RakeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("php", "Pesos (₱)"), ("chips", "Chips")], max_length=8
                    ),
                ),
                ("rake_mode", models.CharField(max_length=8)),
                ("rake_basis_points", models.PositiveIntegerField(default=0)),
                ("rake_flat", models.BigIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="groups.grouprakeaccount",
                    ),
                ),
                (
                    "buy_in",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rake_entry",
                        to="ledger.buyin",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="rake_amount_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit__in", ["php", "chips"])),
                        name="rake_unit_valid",
                    ),
                ],
            },
        ),
    ]
