# Generated by Django 6.1.1 on 2026-10-04 06:09

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_settingsversion_rake_basis_points_and_more"),
        ("groups", "0003_grouprakeaccount"),
        ("ledger", "0011_rakeentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="finalization",
            name="finalization_money_conserved",
        ),
        migrations.AddField(
            model_name="finalization",
            name="total_rake",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerresult",
            name="rake_total",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="finalization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_buy_in",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total_cash_out"), "+", models.F("total_rake")
                        ),
                    )
                ),
                name="finalization_money_conserved",
            ),
        ),
        migrations.AddConstraint(
            model_name="finalization",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_rake__gte", 0)),
                name="finalization_rake_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rake_total__gte", 0),
                    ("rake_total__lte", models.F("buy_in_total")),
                ),
                name="result_rake_valid",
            ),
        ),
    ]
