# Generated by Django 6.1.1 on 2026-10-06 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0012_night_archive"),
        ("ledger", "0012_remove_finalization_finalization_money_conserved_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CountEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                ("request_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_entries",
                        to="games.participant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_entries",
                        to="games.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="finalcount",
            name="entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="confirmations",
                to="ledger.countentry",
            ),
        ),
        migrations.AddConstraint(
            model_name="countentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("participant",),
                name="count_entry_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="countentry",
            constraint=models.UniqueConstraint(
                fields=("participant", "version"), name="count_entry_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="countentry",
            constraint=models.UniqueConstraint(
                fields=("session", "request_id"), name="count_entry_request_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="countentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="count_entry_not_negative"
            ),
        ),
    ]
