# Generated by Django 6.1.1 on 2026-10-03 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0002_gamesession_participant_settingsversion_and_more"),
        ("ledger", "0004_finalization_playerresult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proven_minimal", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finalization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan",
                        to="ledger.finalization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("amount_centavos", models.BigIntegerField()),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_to_receive",
                        to="games.participant",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_to_pay",
                        to="games.participant",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="settlement.settlementplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "position"), name="transfer_position_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_centavos__gt", 0)),
                        name="transfer_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("payer", models.F("payee")), _negated=True),
                        name="transfer_payer_is_not_payee",
                    ),
                ],
            },
        ),
    ]
