# Generated by Django 6.1.1 on 2026-10-03 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_gamenight_night_group_status_date_and_more"),
        ("groups", "0002_invite"),
        ("settlement", "0005_settle_per_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["night"], name="payment_night"),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("night", "request_id"), name="payment_request_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("payer", models.F("payee")), _negated=True),
                name="transfer_payer_is_not_payee",
            ),
        ),
    ]
