"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

from config.deploy import database_config, static_version, vercel_hosts

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# SECURITY WARNING: never run with DEBUG on or the development key in production.
DEBUG = env.bool("DEBUG", default=False)

# A fixed development key is acceptable only while DEBUG is on.
SECRET_KEY = env("SECRET_KEY", default="") or (
    "django-insecure-local-development-only" if DEBUG else ""
)
if not SECRET_KEY:
    raise ImproperlyConfigured("Set SECRET_KEY (or DEBUG=True for local development).")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"]) + vercel_hosts(os.environ)

# HTTPS-only deployment: Secure cookies, HSTS and an HTTPS redirect. On by default
# on Vercel (which sets VERCEL=1, terminates TLS and forwards X-Forwarded-Proto).
HTTPS_ONLY = env.bool("HTTPS_ONLY", default=bool(os.environ.get("VERCEL")))
if HTTPS_ONLY:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31_536_000
    # Subdomains and preloading are a deployment decision (W005, W021). The
    # console mail backend is fine because the app sends no email yet (mail.E001).
    SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021", "mail.E001"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "audit",
    "groups",
    "games",
    "ledger",
    "settlement",
    "web",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.pwa.flags",
            ],
        },
    },
]

AUTH_USER_MODEL = "accounts.User"
# On a public address, an account can be created only from a usable invite link.
# First hosts are added by a superuser in /admin/.
SIGNUP_REQUIRES_INVITE = env.bool("SIGNUP_REQUIRES_INVITE", default=bool(os.environ.get("VERCEL")))
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": database_config(
        env("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=env.int("DB_CONN_MAX_AGE", default=60),
    )
}
if os.environ.get("VERCEL") and "DATABASE_URL" not in os.environ:
    # Vercel's filesystem is not persistent: SQLite there would lose every record.
    raise ImproperlyConfigured("Set DATABASE_URL (Neon Postgres) for Vercel deployments.")
if DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    # File-backed, so threaded tests see the same locking as development.
    DATABASES["default"]["TEST"] = {"NAME": BASE_DIR / "test_db.sqlite3"}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

if "test" in sys.argv:
    # Tests create many users; the production hasher is deliberately slow.
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
    # Tests choose the sign-up rule themselves, also when they run in a Vercel build.
    SIGNUP_REQUIRES_INVITE = False


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
# Stylesheets and scripts carry ?v=<release> on Vercel and are cached for a year (see vercel.json).
STATIC_VERSION = static_version(os.environ)
# Turn off to make installed phones remove the service worker (see config/pwa.py).
SERVICE_WORKER = env.bool("SERVICE_WORKER", default=True)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "config.storage.VersionedStaticStorage"},
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "pokernights": {"handlers": ["console"], "level": env("LOG_LEVEL", default="INFO")},
    },
}
