# Generated by Django 6.1.1 on 2026-10-03 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.BigIntegerField(blank=True, null=True)),
                ("session_id", models.BigIntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "created_at"], name="audit_session_time"
                    ),
                    models.Index(
                        fields=["group_id", "created_at"], name="audit_group_time"
                    ),
                ],
            },
        ),
    ]
