import {spawn} from 'node:child_process';
import {writeFileSync,mkdirSync} from 'node:fs';
const OUT=process.env.PN_REVIEW_DIR || '/private/tmp/pn-rack-review';mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const chrome=spawn(process.env.PN_CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--remote-debugging-port=9341',`--user-data-dir=/private/tmp/pn-rack-chrome`,'--no-first-run','--disable-gpu','about:blank'],{stdio:'ignore'});
let url;for(let i=0;i<40&&!url;i++){try{url=(await(await fetch('http://127.0.0.1:9341/json/version')).json()).webSocketDebuggerUrl;}catch{await sleep(150)}}
const ws=new WebSocket(url);await new Promise(r=>ws.onopen=r);let id=0;const wait=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(wait.has(m.id)){const [ok,no]=wait.get(m.id);wait.delete(m.id);m.error?no(Error(JSON.stringify(m.error))):ok(m.result)}};
const send=(method,params={},sessionId)=>new Promise((ok,no)=>{wait.set(++id,[ok,no]);ws.send(JSON.stringify({id,method,params,sessionId}))});
async function user(name){const {browserContextId}=await send('Target.createBrowserContext');const{targetId}=await send('Target.createTarget',{url:'about:blank',browserContextId});const{sessionId:s}=await send('Target.attachToTarget',{targetId,flatten:true});await send('Page.enable',{},s);await send('Network.enable',{},s);await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},s);
const js=async expression=>{let r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},s);if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
const go=async path=>{await send('Page.navigate',{url:(process.env.PN_BROWSER_URL || 'http://127.0.0.1:8765')+path},s);await sleep(450);for(let i=0;i<30;i++){if(await js('document.readyState')==='complete')break;await sleep(100)}};
const click=async expr=>{await js(expr+'.click()');await sleep(650)};
const shot=async name=>{await js('window.scrollTo(0,0)');await js('document.fonts.ready');const{cssContentSize:size}=await send('Page.getLayoutMetrics',{},s);const{data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:size.width,height:size.height,scale:1}},s);writeFileSync(`${OUT}/${name}.png`,Buffer.from(data,'base64'))};
await go('/accounts/login/');await js(`document.querySelector('[name=username]').value=${JSON.stringify(name)};document.querySelector('[name=password]').value='tablestakes-91';document.querySelector('form.form-section [type=submit]').click()`);await sleep(650);
return {s,js,go,click,shot};}
const results=[];function check(name,ok,detail){results.push({name,ok,detail});console.log(`${ok?'PASS':'FAIL'} ${name} ${detail===undefined?'':JSON.stringify(detail)}`)}
const A=await user('hana'),B=await user('hana'),P=await user('ben');
const errors=[];ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)});await send('Runtime.enable',{},A.s);
const post=async(U,path,data)=>U.js(`(async()=>{const body=new URLSearchParams(${JSON.stringify(data)});body.set('csrfmiddlewaretoken',document.querySelector('[name=csrfmiddlewaretoken]').value);const r=await fetch(${JSON.stringify(path)},{method:'POST',body});return {status:r.status,text:await r.text()};})()`);
try {
// One capture batch of all relevant states, phone and desktop together.
for(const [name,path] of [['counting','/s/2/'],['review','/s/2/cash-out-counted/'],['final','/s/1/'],['balanced','/s/8/'],['discrepancy','/s/9/'],['override','/s/10/'],['no-money','/s/7/'],['chips-count','/s/6/'],['large','/s/11/']]) {
 for(const width of [390,1280]) {
  await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<900},A.s);await A.go(path);await sleep(650);
  check(name+' '+width+' no overflow',await A.js(`document.documentElement.scrollWidth<=${width}`));
  if(width===390&&['counting','no-money','discrepancy'].includes(name))check(name+' visible dock guidance',await A.js(`document.querySelector('.dock-hint').getClientRects().length>0&&getComputedStyle(document.querySelector('.dock-hint')).display!=='none'`));
  if(name==='review')check('review drawn back icon',await A.js(`!!document.querySelector('.table-bar a svg')`));
  if(width===390&&name==='counting')check('progress and totals in first screen',await A.js(`[...document.querySelectorAll('.count-progress,.set-totals')].every(el=>el.getBoundingClientRect().bottom<844)`));
  if(width===1280&&name==='counting')check('count-up two columns',await A.js(`getComputedStyle(document.querySelector('.table-layout')).gridTemplateColumns.split(' ').length===2`));
  await A.shot(name+'-'+width);
 }
}
await send('Emulation.setDeviceMetricsOverride',{width:320,height:844,deviceScaleFactor:1,mobile:true},A.s);await A.go('/s/11/');check('large totals and long names at320 no overflow',await A.js(`document.documentElement.scrollWidth<=320`));await A.shot('large-320');
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},A.s);
await P.go('/s/2/');check('player has read-only counts',await P.js(`!document.querySelector('#counts-form')&&!document.querySelector('.host-controls')&&document.body.textContent.includes('Ready to cash out')`));await P.shot('player-count');
await P.go('/s/1/');check('viewer result and Final label with signs and icon',await P.js(`document.querySelector('.final-amount').textContent.includes('−')&&!!document.querySelector('.final-amount svg')&&document.querySelector('.final-layout .badge').textContent==='Final'&&!document.querySelector('form[action*=paid]')`));await P.shot('player-final');
// Persistent once-only balance rule: fresh context has not visited this set.
await B.go('/s/8/');check('balanced rule first visit animates',await B.js(`document.querySelector('[data-balance]').classList.contains('balance-arrived')`));await B.js(`document.dispatchEvent(new Event('live:updated'))`);await B.go('/s/8/');check('balanced rule reload stays static',await B.js(`!document.querySelector('[data-balance]').classList.contains('balance-arrived')`));
await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]},B.s);await B.go('/s/10/');check('reduce motion disables rule movement',await B.js(`getComputedStyle(document.querySelector('.books-balanced'),'::before').animationName==='none'`));
await A.go('/s/2/');await B.go('/s/2/');
check('one count form and no provisional results',await A.js(`document.querySelectorAll('#counts-form').length===1&&!document.querySelector('.result-amount,.final-amount')`));
const initial=await A.js(`document.querySelector('#live').dataset.version`);
await A.js(`window.field=document.querySelector('[name^=count_]');field.value='777';field.focus()`);
const other=await B.js(`document.querySelector('[name^=count_]').name`);await post(B,'/s/2/counts/confirm/',{[other]:'888',request_id:crypto.randomUUID()});await sleep(4900);
check('second client preserves exact focused field',await A.js(`document.activeElement===field&&field.isConnected&&field.value==='777'`));await A.js(`field.blur()`);await sleep(150);check('draft restored after deferred poll',await A.js(`document.querySelector('[name^=count_]').value==='777'&&document.querySelector('#live').dataset.version!==${JSON.stringify(initial)}`));
const names=await A.js(`[...document.querySelectorAll('[name^=count_]')].map(el=>el.name)`);
await A.js(`document.querySelector('[name=${names[0]}]').value='777';document.querySelector('[name=${names[1]}]').value='abc';document.querySelector('[name=${names[2]}]').value='0'`);const beforeInvalid=await A.js(`document.querySelector('#live').dataset.version`);await A.click(`document.querySelector('button[form=counts-form]')`);
check('invalid multi-count saves nothing and keeps all drafts',await A.js(`document.body.textContent.includes('Nothing was saved')&&document.querySelector('[name=${names[0]}]').value==='777'&&document.querySelector('[name=${names[1]}]').value==='abc'&&document.querySelector('[name=${names[2]}]').value==='0'&&document.querySelector('#live').dataset.version===${JSON.stringify(beforeInvalid)}`));
await A.js(`document.querySelector('[name=${names[1]}]').value='0';document.querySelector('[name=${names[3]}]').value=''`);await A.click(`document.querySelector('button[form=counts-form]')`);
check('one button confirms typed counts including zero, skips empty',await A.js(`document.querySelector('[name=${names[2]}]').closest('.count-row').textContent.includes('Counted ₱0')&&document.querySelector('[name=${names[3]}]').closest('.count-row').querySelector('[data-status]').dataset.status==='awaiting'`));
await A.go('/s/2/cash-out-counted/');const reviewed=await A.js(`[...document.querySelectorAll('[name=count_id]')].map(el=>el.value)`);await B.go('/s/2/');await post(B,'/s/2/counts/confirm/',{[names[0]]:'700',request_id:crypto.randomUUID()});await A.click(`document.querySelector('.batch-review button[type=submit]')`);
check('stale review rejects and shows fresh exact count IDs',await A.js(`document.querySelector('[role=alert]').textContent.includes('Nothing was recorded')&&document.body.textContent.includes('₱700')&&![...document.querySelectorAll('[name=count_id]')].every(el=>${JSON.stringify(reviewed)}.includes(el.value))`));
// Native flows without JavaScript: counts -> review -> cash-outs -> finalization.
await send('Emulation.setScriptExecutionDisabled',{value:true},B.s);await B.go('/s/6/');check('chips count-up no peso',await B.js(`!document.body.textContent.includes('₱')`));await B.js(`const fields=[...document.querySelectorAll('[name^=count_]')];fields[0].value='1900';fields[1].value='0'`);await B.click(`document.querySelector('button[form=counts-form]')`);await B.click(`document.querySelector('.next-action')`);check('chips review no peso and prospective total',await B.js(`!document.body.textContent.includes('₱')&&document.body.textContent.includes('2,000 chips')`));await B.click(`document.querySelector('.batch-review button[type=submit]')`);check('native batch offers finalize only when balanced',await B.js(`document.body.textContent.includes('Finalize results')`));await B.click(`document.querySelector('.next-action')`);check('native finalization frozen chips results',await B.js(`!!document.querySelector('.final-results')&&!document.querySelector('#counts-form')&&!document.body.textContent.includes('₱')`));await B.shot('chips-final');
// No-JS correction path stays available during reconciliation.
await B.go('/s/9/');await B.js(`document.querySelector('[data-key^=player-]').open=true;window.reverse=[...document.querySelectorAll('form[action*=cashouts][action$="reverse/"]')].find(f=>f.closest('li').textContent.includes('Final cash-out'));reverse.querySelector('[name=reason]').value='Synthetic recount correction'`);await B.click(`reverse.querySelector('button')`);check('native reversal returns participant to countable state',await B.js(`!!document.querySelector('[name^=count_]')&&document.body.textContent.includes('Reversed: Synthetic recount correction')`));
// Labels, focus and dock clearance at the bottom of the document.
await A.go('/s/11/');await A.js(`document.querySelector('[name^=count_]').focus()`);check('count actions have48px targets',await A.js(`[...document.querySelectorAll('button[form=counts-form],.host-more>summary')].every(el=>el.getBoundingClientRect().height>=48)`));check('count field keyboard focus visible and labelled',await A.js(`document.activeElement.labels.length===1&&getComputedStyle(document.activeElement).outlineWidth==='3px'`));await A.js(`window.scrollTo(0,document.documentElement.scrollHeight)`);check('host dock clears last count action',await A.js(`document.querySelector('button[form=counts-form].btn-block').getBoundingClientRect().bottom<=document.querySelector('.host-controls').getBoundingClientRect().top`));
const contrast=await A.js(`(()=>{const c=document.createElement('canvas').getContext('2d',{willReadFrequently:true});const v=getComputedStyle(document.documentElement);const lum=n=>{c.fillStyle=v.getPropertyValue(n);c.fillRect(0,0,1,1);let a=[...c.getImageData(0,0,1,1).data].slice(0,3).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return .2126*a[0]+.7152*a[1]+.0722*a[2]};return [['--slate-ink','--slate'],['--bone','--slate'],['--up','--slate'],['--down','--slate']].map(([a,b])=>{let x=lum(a),y=lum(b);return {pair:[a,b],ratio:(Math.max(x,y)+.05)/(Math.min(x,y)+.05)}})})()`);check('slate text contrast >=4.5',contrast.every(x=>x.ratio>=4.5),contrast);
check('no browser runtime errors',errors.length===0,errors);
writeFileSync(`${OUT}/end-set.json`,JSON.stringify(results,null,2));
} finally {await send('Browser.close');ws.close();chrome.kill();}
if(results.some(x=>!x.ok))process.exitCode=1;
