import {spawn} from 'node:child_process';
import {writeFileSync,mkdirSync,readFileSync} from 'node:fs';
const OUT=process.env.PN_REVIEW_DIR || '/private/tmp/pn-rack-review';mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const chrome=spawn(process.env.PN_CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--remote-debugging-port=9341',`--user-data-dir=/private/tmp/pn-rack-chrome`,'--no-first-run','--disable-gpu','about:blank'],{stdio:'ignore'});
let url;for(let i=0;i<40&&!url;i++){try{url=(await(await fetch('http://127.0.0.1:9341/json/version')).json()).webSocketDebuggerUrl;}catch{await sleep(150)}}
const ws=new WebSocket(url);await new Promise(r=>ws.onopen=r);let id=0;const wait=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(wait.has(m.id)){const [ok,no]=wait.get(m.id);wait.delete(m.id);m.error?no(Error(JSON.stringify(m.error))):ok(m.result)}};
const send=(method,params={},sessionId)=>new Promise((ok,no)=>{wait.set(++id,[ok,no]);ws.send(JSON.stringify({id,method,params,sessionId}))});
async function user(name){const {browserContextId}=await send('Target.createBrowserContext');const{targetId}=await send('Target.createTarget',{url:'about:blank',browserContextId});const{sessionId:s}=await send('Target.attachToTarget',{targetId,flatten:true});await send('Page.enable',{},s);await send('Network.enable',{},s);await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},s);
const js=async expression=>{let r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},s);if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
const go=async path=>{await send('Page.navigate',{url:(process.env.PN_BROWSER_URL || 'http://127.0.0.1:8765')+path},s);await sleep(450);for(let i=0;i<30;i++){if(await js('document.readyState')==='complete')break;await sleep(100)}};
const click=async expr=>{await js(expr+'.click()');await sleep(650)};
const shot=async name=>{await js('window.scrollTo(0,0)');await js('document.fonts.ready');const{cssContentSize:size}=await send('Page.getLayoutMetrics',{},s);const{data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:size.width,height:size.height,scale:1}},s);writeFileSync(`${OUT}/${name}.png`,Buffer.from(data,'base64'))};
await go('/accounts/login/');await js(`document.querySelector('[name=username]').value=${JSON.stringify(name)};document.querySelector('[name=password]').value='tablestakes-91';document.querySelector('form.form-section [type=submit]').click()`);await sleep(650);
return {s,js,go,click,shot};}
const results=[];function check(name,ok,detail){results.push({name,ok,detail});console.log(`${ok?'PASS':'FAIL'} ${name} ${detail===undefined?'':JSON.stringify(detail)}`)}
const A=await user('hana'),B=await user('hana'),P=await user('ben');
const errors=[];ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)});await send('Runtime.enable',{},A.s);
const post=async(U,path,data)=>U.js(`(async()=>{const body=new URLSearchParams(${JSON.stringify(data)});body.set('csrfmiddlewaretoken',document.querySelector('[name=csrfmiddlewaretoken]').value);const r=await fetch(${JSON.stringify(path)},{method:'POST',body});return {status:r.status,text:await r.text()};})()`);
const nights=JSON.parse(readFileSync('/private/tmp/pn-slice3-manifest.json','utf8'));
const path=n=>'/n/'+nights[n]+'/';
const dismiss=async U=>{if(await U.js(`!!document.querySelector('dialog[open]')`))await U.click(`document.querySelector('.sheet-head button')`)};
try {
for(const name of ['partly','unpaid','settled','break-even','large','ready','blocked','empty','tied']) {
 for(const width of [390,1280]) {
  await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<900},A.s);await A.go(path(name));await sleep(600);
  if(await A.js(`!!document.querySelector('dialog[open]')`)){await A.shot(name+'-recap-'+width);await dismiss(A)}
  check(name+' '+width+' no overflow',await A.js(`document.documentElement.scrollWidth<=${width}`));
  if(width===1280)check(name+' desktop columns',await A.js(`getComputedStyle(document.querySelector('.night-layout')).gridTemplateColumns.split(' ').length===2`));
  await A.shot(name+'-'+width);
  if(width===1280&&await A.js(`!!document.querySelector('[data-sheet-open=recap]')`)){await A.click(`document.querySelector('[data-sheet-open=recap]')`);await A.shot(name+'-recap-1280');await dismiss(A)}
 }
}
await send('Emulation.setDeviceMetricsOverride',{width:320,height:844,deviceScaleFactor:1,mobile:true},A.s);await A.go(path('large'));await dismiss(A);check('large amount remains one line',await A.js(`document.querySelector('[data-still-to-pay]').getBoundingClientRect().height<40`));check('large transfer names and amounts fit320',await A.js(`document.documentElement.scrollWidth<=320`));await A.shot('large-320');
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},A.s);
await P.go(path('unpaid'));check('player first visit opens own recap',await P.js(`!!document.querySelector('dialog[open]')&&document.querySelector('.sheet-body').textContent.includes('Your session result')`));await P.shot('player-recap');await dismiss(P);check('close returns focus to recap trigger',await P.js(`document.activeElement.dataset.sheetOpen==='recap'`));await P.go(path('unpaid'));check('player reload does not autoopen',await P.js(`!document.querySelector('dialog[open]')`));check('player has no write controls',await P.js(`!document.querySelector('form[action*=transfers]')`));await P.shot('player-unpaid');
await P.click(`document.querySelector('[data-sheet-open=recap]')`);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9},P.s);check('Tab keeps modal open and focus inside',await P.js(`!!document.querySelector('dialog[open]')&&document.querySelector('dialog').contains(document.activeElement)`));await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},P.s);await sleep(300);check('Escape closes recap',await P.js(`!document.querySelector('dialog[open]')`));
await P.go(path('settled'));check('another session autoopens',await P.js(`!!document.querySelector('dialog[open]')`));await dismiss(P);
await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]},P.s);await P.go(path('tied'));check('reduced motion recap lines static',await P.js(`[...document.querySelectorAll('.sheet-body .recap-lines>div')].every(el=>getComputedStyle(el).animationName==='none')`));await P.shot('reduced-recap');await dismiss(P);
const D=await user('hana');await send('Page.addScriptToEvaluateOnNewDocument',{source:`Storage.prototype.setItem=function(){throw Error('Synthetic storage refusal')}`},D.s);await D.go(path('unpaid'));check('storage refusal skips autoopen',await D.js(`!document.querySelector('dialog[open]')`));await D.click(`document.querySelector('[data-sheet-open=recap]')`);check('storage refusal allows manual recap',await D.js(`!!document.querySelector('dialog[open]')`));await dismiss(D);
await A.go(path('unpaid'));await B.go(path('unpaid'));await dismiss(B);const before=await A.js(`document.querySelector('[data-still-to-pay]').dataset.stillToPay`);const frozen=await A.js(`document.querySelector('.night-results').textContent`);const paySelector=`document.querySelector('form[action$="/paid/"] button')`;const transfer=await A.js(`document.querySelector('form[action$="/paid/"]').getAttribute('action')`);
await A.click(paySelector);check('paid redirect no recap and amount changes',await A.js(`!document.querySelector('dialog[open]')&&document.querySelector('[data-still-to-pay]').dataset.stillToPay!==${JSON.stringify(before)}`));check('payment leaves session result unchanged',await A.js(`document.querySelector('.night-results').textContent===${JSON.stringify(frozen)}`));check('other client remains reload-based',await B.js(`document.querySelector('[data-still-to-pay]').dataset.stillToPay===${JSON.stringify(before)}`));await B.go(path('unpaid'));check('other client refresh gets accepted state',await B.js(`document.querySelector('[data-still-to-pay]').dataset.stillToPay!==${JSON.stringify(before)}`));await post(A,transfer,{request_id:crypto.randomUUID()});await A.go(path('unpaid'));check('repeated paid does not double-record',await A.js(`document.querySelectorAll('.payment-records li').length===1`));
await A.click(`document.querySelector('form[action$="/unpaid/"] button')`);check('undo restores amount and preserves record',await A.js(`document.querySelector('[data-still-to-pay]').dataset.stillToPay===${JSON.stringify(before)}&&document.querySelector('.payment-records').textContent.includes('undone')&&!document.querySelector('dialog[open]')`));
await send('Emulation.setScriptExecutionDisabled',{value:true},B.s);await B.go(path('unpaid'));check('no JS inline recap and native forms visible',await B.js(`document.querySelector('.recap-source').getClientRects().length>0&&!!document.querySelector('form[action$="/paid/"]')`));await B.shot('no-js-recap');await B.click(paySelector);await B.click(`document.querySelector('form[action$="/unpaid/"] button')`);check('no JS paid then undo restores accepted amount',await B.js(`document.querySelector('[data-still-to-pay]').dataset.stillToPay===${JSON.stringify(before)}&&document.querySelectorAll('.payment-records li').length===2`));
await B.go(path('ready'));check('ready offers close',await B.js(`!!document.querySelector('form[action$="/close/"]')`));await B.click(`document.querySelector('form[action$="/close/"] button')`);check('native close creates transfer instructions',await B.js(`!!document.querySelector('#transfers-title')&&document.body.textContent.includes('Session closed')`));await B.go(path('next-ready'));await B.click(`document.querySelector('form[action$="/next-set/"] button')`);check('native next set navigates to set2',await B.js(`document.body.textContent.includes('Set 2 is open')`));
await A.go(path('unpaid'));check('interactive targets48px',await A.js(`[...document.querySelectorAll('.table-bar>a, .set-link, .recap-opener, .transfer-row button')].every(el=>el.getBoundingClientRect().height>=48)`));await A.js(`document.querySelector('.recap-opener').focus()`);check('keyboard focus visible',await A.js(`getComputedStyle(document.activeElement).outlineWidth==='3px'`));check('no browser runtime errors',errors.length===0,errors);
writeFileSync(`${OUT}/night.json`,JSON.stringify(results,null,2));
} finally {await send('Browser.close');ws.close();chrome.kill();}
if(results.some(x=>!x.ok))process.exitCode=1;
