import {spawn} from 'node:child_process';
import {writeFileSync,mkdirSync} from 'node:fs';
const OUT=process.env.PN_REVIEW_DIR || '/private/tmp/pn-rack-review';mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const chrome=spawn(process.env.PN_CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--remote-debugging-port=9341',`--user-data-dir=/private/tmp/pn-rack-chrome`,'--no-first-run','--disable-gpu','about:blank'],{stdio:'ignore'});
let url;for(let i=0;i<40&&!url;i++){try{url=(await(await fetch('http://127.0.0.1:9341/json/version')).json()).webSocketDebuggerUrl;}catch{await sleep(150)}}
const ws=new WebSocket(url);await new Promise(r=>ws.onopen=r);let id=0;const wait=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(wait.has(m.id)){const [ok,no]=wait.get(m.id);wait.delete(m.id);m.error?no(Error(JSON.stringify(m.error))):ok(m.result)}};
const send=(method,params={},sessionId)=>new Promise((ok,no)=>{wait.set(++id,[ok,no]);ws.send(JSON.stringify({id,method,params,sessionId}))});
async function user(name){const {browserContextId}=await send('Target.createBrowserContext');const{targetId}=await send('Target.createTarget',{url:'about:blank',browserContextId});const{sessionId:s}=await send('Target.attachToTarget',{targetId,flatten:true});await send('Page.enable',{},s);await send('Network.enable',{},s);await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},s);
const js=async expression=>{let r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},s);if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
const go=async path=>{await send('Page.navigate',{url:(process.env.PN_BROWSER_URL || 'http://127.0.0.1:8765')+path},s);await sleep(450);for(let i=0;i<30;i++){if(await js('document.readyState')==='complete')break;await sleep(100)}};
const click=async expr=>{await js(expr+'.click()');await sleep(650)};
const shot=async name=>{await js('window.scrollTo(0,0)');await js('document.fonts.ready');const{data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},s);writeFileSync(`${OUT}/${name}.png`,Buffer.from(data,'base64'))};
await go('/accounts/login/');await js(`document.querySelector('[name=username]').value=${JSON.stringify(name)};document.querySelector('[name=password]').value='tablestakes-91';document.querySelector('form.form-section button').click()`);await sleep(650);
return {s,js,go,click,shot};}
const results=[];function check(name,ok,detail){results.push({name,ok,detail});console.log(`${ok?'PASS':'FAIL'} ${name} ${detail===undefined?'':JSON.stringify(detail)}`)}
const A=await user('hana'),B=await user('hana');await send('Page.addScriptToEvaluateOnNewDocument',{source: "window.loadShifts=[];new PerformanceObserver(l=>loadShifts.push(...l.getEntries().filter(x=>!x.hadRecentInput).map(x=>x.value))).observe({type:'layout-shift',buffered:true});"},A.s);await A.go('/s/3/');await sleep(500);check('font and initial layout shifts below .05',await A.js(`loadShifts.reduce((a,b)=>a+b,0)<.05`),await A.js('loadShifts'));await B.go('/s/3/');
const contrasts=await A.js(`(() => {
const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
function rgb(c){ctx.fillStyle=c;ctx.fillRect(0,0,1,1);return [...ctx.getImageData(0,0,1,1).data].slice(0,3).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4})}
function lum(c){const a=rgb(c);return .2126*a[0]+.7152*a[1]+.0722*a[2]}
const style=getComputedStyle(document.documentElement),v=n=>style.getPropertyValue(n).trim();
const pairs=[['body','--bone','--ground',4.5],['muted','--bone-dim','--ground',4.5],['sheet','--bone-dim','--rail',4.5],['felt','--felt-ink','--felt',4.5],['bone on felt','--bone','--felt',4.5],['primary','--ink','--bone',4.5],['danger','--down','--danger-bg',4.5],['input edge','--line','--ground',3],['button edge','--line','--rail-2',3]];
const out=pairs.map(([name,fg,bg,min])=>{let a=lum(v(fg)),b=lum(v(bg));return {name,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),min}});
for(let i=1;i<=10;i++){let a=lum(i>=4&&i<=9&&i!==5?v('--ink'):'#fff'),b=lum(v('--c'+i));out.push({name:'token'+i,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),min:4.5})}
return out;
})()`);check('all text and control contrast pairs meet target',contrasts.every(x=>x.ratio>=x.min),contrasts);
await A.click(`document.querySelector('.buy-opener')`);
await A.js(`document.querySelector('.sheet-head button').focus()`);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,modifiers:8},A.s);await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,modifiers:8},A.s);
check('Shift-Tab wraps focus to final control',await A.js(`document.activeElement===document.querySelector('dialog button[type=submit]')`));
await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9},A.s);await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9},A.s);check('Tab wraps focus to close',await A.js(`document.activeElement===document.querySelector('.sheet-head button')`));
await A.click(`document.querySelector('.sheet-head button')`);
await send('Emulation.setCPUThrottlingRate',{rate:4},A.s);await A.js(`window.tasks=[];window.shifts=[];new PerformanceObserver(l=>tasks.push(...l.getEntries().map(x=>x.duration))).observe({type:'longtask',buffered:false});new PerformanceObserver(l=>shifts.push(...l.getEntries().filter(x=>!x.hadRecentInput).map(x=>x.value))).observe({type:'layout-shift',buffered:false})`);await A.click(`document.querySelector('.buy-opener')`);await sleep(800);await A.click(`document.querySelector('.sheet-head button')`);check('4x CPU sheet motion has no long task over50ms',await A.js(`tasks.every(x=>x<=50)`),await A.js('tasks'));check('sheet layout shift below .05',await A.js(`shifts.reduce((a,b)=>a+b,0)<.05`),await A.js('shifts'));await send('Emulation.setCPUThrottlingRate',{rate:1},A.s);
await A.go('/s/2/');await B.go('/s/2/');await A.js(`window.field=document.querySelector('[name^=count_]');field.value='777';field.focus()`);const prior=await B.js(`document.querySelector('#live').dataset.version`);await B.js(`const fields=[...document.querySelectorAll('[name^=count_]')];[String(Number(document.querySelector('#live').dataset.version)+100),'0',String(Number(document.querySelector('#live').dataset.version)+200)].forEach((v,i)=>fields[i].value=v);document.querySelector('button[form=counts-form]').click()`);await sleep(700);check('one count button confirms three fields, including zero',await B.js(`document.querySelector('#live').dataset.version!==${JSON.stringify(prior)} && [...document.querySelectorAll('[name^=count_]')].slice(0,3).every(el=>el.closest('li').querySelector('[data-status]').dataset.status==='ready') && document.body.textContent.includes('Counted ₱0')`));await sleep(5000);check('live refresh does not replace focused count field',await A.js(`document.activeElement===field && field.isConnected && field.value==='777'`));await A.js(`field.blur()`);await sleep(100);check('unsaved count restored after focus leaves',await A.js(`document.querySelector('[name^=count_]').value==='777'`));
await A.go('/s/3/');await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:-1,uploadThroughput:-1},A.s);await sleep(12500);check('two failed polls show stale state',await A.js(`document.querySelector('#live-status').textContent.includes('Reconnecting') && document.querySelector('#live').classList.contains('is-stale')`));await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1},A.s);await A.js(`window.dispatchEvent(new Event('online'))`);await sleep(200);check('successful poll restores live state',await A.js(`!document.querySelector('#live').classList.contains('is-stale')`));
// A second host with scripts disabled submits the native fallback forms.
await send('Emulation.setScriptExecutionDisabled',{value:true},B.s);await B.go('/s/3/');const before=await B.js(`document.querySelector('.player-row').dataset.value`);await B.js(`document.querySelector('[data-sheet-source^=buy-]').open=true;document.querySelector('[data-sheet-source^=buy-] button[type=submit]').click()`);await sleep(700);check('no-JS host buy-in succeeds',await B.js(`document.querySelector('.player-row').dataset.value!==${JSON.stringify(before)}`));const cashBefore=await B.js(`Number(document.querySelector('.player-row').dataset.value.split(':')[2])`);await B.js(`document.querySelector('[data-sheet-source^=player-]').open=true;document.querySelector('form[action$="cashouts/add/"] [name=amount]').value='100';document.querySelector('form[action$="cashouts/add/"] button[type=submit]').click()`);await sleep(700);check('no-JS host cash-out succeeds',await B.js(`Number(document.querySelector('.player-row').dataset.value.split(':')[2])===${cashBefore}+10000`));
writeFileSync(`${OUT}/accessibility.json`,JSON.stringify(results,null,2));await send('Browser.close');ws.close();chrome.kill();if(results.some(x=>!x.ok))process.exitCode=1;
