import {spawn} from 'node:child_process';
import {writeFileSync,mkdirSync} from 'node:fs';
const OUT=process.env.PN_REVIEW_DIR || '/private/tmp/pn-rack-review';mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const chrome=spawn(process.env.PN_CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--remote-debugging-port=9341',`--user-data-dir=/private/tmp/pn-rack-chrome`,'--no-first-run','--disable-gpu','about:blank'],{stdio:'ignore'});
let url;for(let i=0;i<40&&!url;i++){try{url=(await(await fetch('http://127.0.0.1:9341/json/version')).json()).webSocketDebuggerUrl;}catch{await sleep(150)}}
const ws=new WebSocket(url);await new Promise(r=>ws.onopen=r);let id=0;const wait=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(wait.has(m.id)){const [ok,no]=wait.get(m.id);wait.delete(m.id);m.error?no(Error(JSON.stringify(m.error))):ok(m.result)}};
const send=(method,params={},sessionId)=>new Promise((ok,no)=>{wait.set(++id,[ok,no]);ws.send(JSON.stringify({id,method,params,sessionId}))});
async function user(name){const {browserContextId}=await send('Target.createBrowserContext');const{targetId}=await send('Target.createTarget',{url:'about:blank',browserContextId});const{sessionId:s}=await send('Target.attachToTarget',{targetId,flatten:true});await send('Page.enable',{},s);await send('Network.enable',{},s);await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},s);
const js=async expression=>{let r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},s);if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
const go=async path=>{await send('Page.navigate',{url:(process.env.PN_BROWSER_URL || 'http://127.0.0.1:8765')+path},s);await sleep(450);for(let i=0;i<30;i++){if(await js('document.readyState')==='complete')break;await sleep(100)}};
const click=async expr=>{await js(expr+'.click()');await sleep(650)};
const shot=async name=>{await js('window.scrollTo(0,0)');await js('document.fonts.ready');const{data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},s);writeFileSync(`${OUT}/${name}.png`,Buffer.from(data,'base64'))};
await go('/accounts/login/');await js(`document.querySelector('[name=username]').value=${JSON.stringify(name)};document.querySelector('[name=password]').value='tablestakes-91';document.querySelector('form.form-section [type=submit]').click()`);await sleep(650);
return {s,js,go,click,shot};}
const results=[];function check(name,ok,detail){results.push({name,ok,detail});console.log(`${ok?'PASS':'FAIL'} ${name} ${detail===undefined?'':JSON.stringify(detail)}`)}
const A=await user('hana'),B=await user('hana'),P=await user('ben');
const row="document.querySelector('.player-row')";
await A.go('/s/3/');await B.go('/s/3/');
const dimensions=await A.js(`({height:document.documentElement.scrollHeight,width:document.documentElement.scrollWidth,viewport:innerWidth,rows:document.querySelectorAll('.player-row').length})`);check('phone 8-player height <=1200',dimensions.height<=1200,dimensions);check('phone no overflow',dimensions.width<=390,dimensions);
await A.shot('mobile');
const bounds=await A.js(`Array.from(document.querySelectorAll('.display-amount,.pot-side')).map(el=>el.getBoundingClientRect().bottom)`);check('money, clock, blinds in first viewport',bounds.every(x=>x<844),bounds);
const opener=await A.js(`${row}.querySelector('.buy-opener').dataset.sheetOpen`);
await A.click(`${row}.querySelector('.buy-opener')`);check('sheet opens with default and range',await A.js(`document.querySelector('dialog').open && document.querySelector('dialog [name=amount]').value==='1000' && document.querySelector('dialog').textContent.includes('Allowed:')`));
await A.shot('sheet');
check('sheet focuses input',await A.js(`document.activeElement===document.querySelector('dialog [name=amount]')`));
await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},A.s);await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},A.s);await sleep(300);
check('Escape closes and returns focus',await A.js(`!document.querySelector('dialog').open && document.activeElement.dataset.sheetOpen===${JSON.stringify(opener)}`));
await A.click(`${row}.querySelector('.buy-opener')`);
const before=await A.js(`${row}.dataset.value`);
await A.click(`document.querySelector('dialog button[type=submit]')`);
check('default rebuy in two taps changes server row',await A.js(`${row}.dataset.value !== ${JSON.stringify(before)}`));check('accepted row highlighted',await A.js(`${row}.classList.contains('just-changed')`));
await A.click(`${row}.querySelector('.buy-opener')`);await A.js(`window.kept=document.querySelector('dialog [name=amount]');kept.value='1250';kept.focus()`);
await B.go('/s/3/');await B.click(`document.querySelectorAll('.player-row')[1].querySelector('.buy-opener')`);await B.click(`document.querySelector('dialog button[type=submit]')`);await sleep(4700);
check('live refresh preserves open sheet, exact focused field and typing',await A.js(`document.querySelector('dialog').open && document.activeElement===window.kept && kept.value==='1250'`));
await A.click(`document.querySelector('.sheet-head button')`);await sleep(3300);await A.js(`document.dispatchEvent(new Event('live:updated'))`);check('same values do not highlight',await A.js(`!document.querySelector('#live .just-changed')`));
await A.click(`${row}.querySelector('.buy-opener')`);await A.js(`document.querySelector('dialog [name=amount]').value='abc'`);const invalidBefore=await A.js(`${row}.dataset.value`);await A.click(`document.querySelector('dialog button[type=submit]')`);
check('refused amount reopens sheet with field error and typed value',await A.js(`document.querySelector('dialog').open && document.querySelector('dialog [name=amount]').value==='abc' && !!document.querySelector('dialog [aria-invalid=true]') && document.querySelector('.player-row').dataset.value===${JSON.stringify(invalidBefore)}`));
await A.click(`document.querySelector('.sheet-head button')`);await A.click(`${row}.querySelector('.cash-opener')`);const cashBefore=await A.js(`${row}.dataset.value.split(':')[2]`);await A.js(`document.querySelector('dialog form[action$="cashouts/add/"] [name=amount]').value='500'`);await A.click(`document.querySelector('dialog form[action$="cashouts/add/"] button[type=submit]')`);check('cash-out sheet records amount',await A.js(`Number(${row}.dataset.value.split(':')[2])===Number(${JSON.stringify(cashBefore)})+50000`));
await A.click(`${row}.querySelector('.player-opener')`);await A.js(`Array.from(document.querySelectorAll('dialog form[action*="cashouts/"][action$="reverse/"] [name=reason]')).at(-1).value='Browser check correction'`);await A.click(`Array.from(document.querySelectorAll('dialog form[action*="cashouts/"][action$="reverse/"] button[type=submit]')).at(-1)`);check('correction reverses cash-out',await A.js(`${row}.dataset.value.split(':')[2]===${JSON.stringify(cashBefore)}`));
await P.go('/s/3/');check('player has no buy-in or host controls',await P.js(`!document.querySelector('.buy-opener') && !document.querySelector('.next-action')`));await P.shot('player');
await A.go('/s/5/');check('chips amounts without peso',await A.js(`!document.body.textContent.includes('₱') && document.querySelector('.display-amount').textContent.includes('chips')`));check('chips no overflow',await A.js(`document.documentElement.scrollWidth<=390`));await A.shot('chips');
await A.go('/s/2/');check('count-up keeps one form and no result figures',await A.js(`document.querySelectorAll('#counts-form').length===1 && !!document.querySelector('[form=counts-form]') && !document.body.textContent.includes('Your result in set')`));await A.shot('counting');
await A.go('/s/4/');await A.shot('empty');await A.go('/s/1/');await A.shot('final');
await A.go('/');await A.shot('home');await A.go('/g/1/');await A.shot('group');
await A.go('/s/3/');await send('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false},A.s);await sleep(200);await A.shot('desktop');check('desktop has two columns and text actions',await A.js(`getComputedStyle(document.querySelector('.table-layout')).gridTemplateColumns.split(' ').length===2 && getComputedStyle(document.querySelector('.desktop-label')).display!=='none'`));
await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]},A.s);await A.click(`${row}.querySelector('.buy-opener')`);check('reduced motion has no sheet animation or button transform',await A.js(`getComputedStyle(document.querySelector('dialog')).animationName==='none' && getComputedStyle(document.querySelector('dialog .btn')).transitionDuration==='0s'`));await A.click(`document.querySelector('.sheet-head button')`);
await send('Emulation.setScriptExecutionDisabled',{value:true},P.s);await P.go('/s/3/');check('without JS details fallback visible',await P.js(`!document.documentElement.classList.contains('sheets-enabled') && getComputedStyle(document.querySelector('.sheet-source')).display!=='none'`));
writeFileSync(`${OUT}/flows.json`,JSON.stringify(results,null,2));await send('Browser.close');ws.close();chrome.kill();if(results.some(x=>!x.ok))process.exitCode=1;
