import {spawn} from 'node:child_process';
import {writeFileSync,mkdirSync,readFileSync} from 'node:fs';
const OUT=process.env.PN_REVIEW_DIR || '/private/tmp/pn-rake-review';mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const chrome=spawn(process.env.PN_CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--remote-debugging-port=9341',`--user-data-dir=/private/tmp/pn-rack-chrome`,'--no-first-run','--disable-gpu','about:blank'],{stdio:'ignore'});
let url;for(let i=0;i<40&&!url;i++){try{url=(await(await fetch('http://127.0.0.1:9341/json/version')).json()).webSocketDebuggerUrl;}catch{await sleep(150)}}
const ws=new WebSocket(url);await new Promise(r=>ws.onopen=r);let id=0;const wait=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(wait.has(m.id)){const [ok,no]=wait.get(m.id);wait.delete(m.id);m.error?no(Error(JSON.stringify(m.error))):ok(m.result)}};
const send=(method,params={},sessionId)=>new Promise((ok,no)=>{wait.set(++id,[ok,no]);ws.send(JSON.stringify({id,method,params,sessionId}))});
async function user(name){const {browserContextId}=await send('Target.createBrowserContext');const{targetId}=await send('Target.createTarget',{url:'about:blank',browserContextId});const{sessionId:s}=await send('Target.attachToTarget',{targetId,flatten:true});await send('Page.enable',{},s);await send('Network.enable',{},s);await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},s);
const js=async expression=>{let r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},s);if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
const go=async path=>{await send('Page.navigate',{url:(process.env.PN_BROWSER_URL || 'http://127.0.0.1:8765')+path},s);await sleep(450);for(let i=0;i<30;i++){if(await js('document.readyState')==='complete')break;await sleep(100)}};
const click=async expr=>{await js(expr+'.click()');await sleep(650)};
const shot=async name=>{await js('window.scrollTo(0,0)');await js('document.fonts.ready');const{cssContentSize:size}=await send('Page.getLayoutMetrics',{},s);const{data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:size.width,height:size.height,scale:1}},s);writeFileSync(`${OUT}/${name}.png`,Buffer.from(data,'base64'))};
await go('/accounts/login/');await js(`document.querySelector('[name=username]').value=${JSON.stringify(name)};document.querySelector('[name=password]').value='tablestakes-91';document.querySelector('form.form-section button').click()`);await sleep(650);
return {s,js,go,click,shot};}
const A=await user('hana'),ids=JSON.parse(readFileSync('/private/tmp/pn-rake-manifest.json','utf8'));const results=[];
function check(name,ok){results.push({name,ok});console.log(`${ok?'PASS':'FAIL'} ${name}`)}
async function finish(amounts){await A.click(`document.querySelector('.next-action')`);await A.js(`document.querySelectorAll('[data-count-input]').forEach((f,i)=>f.value=${JSON.stringify(amounts)}[i])`);await A.click(`document.querySelector('button[form=counts-form].btn-block')`);await A.click(`document.querySelector('a.next-action')`);await A.click(`document.querySelector('form.batch-review button')`);check('rake books balance',await A.js(`document.body.textContent.includes('Cash-outs plus rake equal gross buy-ins')`));await A.click(`document.querySelector('.next-action')`);const p=await A.js(`document.querySelector('.session-next a').getAttribute('href')`);await A.go(p);return p;}
try {
await send('Emulation.setScriptExecutionDisabled',{value:true},A.s);
await A.go(`/s/${ids.percent}/`);const mixed=await finish(['1900','950','950']);
await A.click(`document.querySelector('form[action$="/next-set/"] button')`);check('next set inherits percentage',await A.js(`document.body.textContent.includes('5% rake deducted')`));
const settings=await A.js(`document.querySelector('a[href$="/settings/"]').getAttribute('href')`);await A.go(settings);await A.js(`document.querySelector('[name=rake_mode]').value='off'`);await A.click(`document.querySelector('form.form-section button')`);await A.click(`document.querySelector('.next-action')`);
await A.click(`document.querySelector('.next-action')`);await A.js(`document.querySelectorAll('[data-count-input]').forEach(f=>f.value='1000')`);await A.click(`document.querySelector('button[form=counts-form].btn-block')`);await A.click(`document.querySelector('a.next-action')`);await A.click(`document.querySelector('form.batch-review button')`);await A.click(`document.querySelector('.next-action')`);await A.go(mixed);await A.click(`document.querySelector('form[action$="/close/"] button')`);
check('mixed Off and percentage session no duplicate charge',await A.js(`document.body.textContent.includes('Nobody owes anything')&&document.body.textContent.includes('₱200')`));
await A.go(`/s/${ids.flat}/`);await finish(['980','980']);await A.click(`document.querySelector('form[action$="/close/"] button')`);check('flat chips close without extra fee',await A.js(`document.body.textContent.includes('Nobody owes anything')&&document.body.textContent.includes('40 chips')`));
for(const [key,mode,rate,flat,counts,pool] of [['percentchips','percent','5','',['950','950'],'100 chips'],['flatphp','flat','','20.50',['979.50','979.50'],'₱41']]) {
await A.go(`/s/${ids[key]}/settings/`);await A.js(`document.querySelector('[name=rake_mode]').value=${JSON.stringify(mode)};document.querySelector('[name=rake_percentage]').value=${JSON.stringify(rate)};document.querySelector('[name=rake_flat]').value=${JSON.stringify(flat)}`);await A.click(`document.querySelector('form.form-section button')`);check(key+' native settings',await A.js(`!location.pathname.endsWith('/settings/')`));await A.click(`document.querySelector('.next-action')`);await finish(counts);await A.click(`document.querySelector('form[action$="/close/"] button')`);check(key+' exact native pool and zero transfers',await A.js(`document.body.textContent.includes(${JSON.stringify(pool)})&&document.body.textContent.includes('Nobody owes anything')`));
}
await A.go(`/g/${ids.group}/`);check('all native unit pools reconcile',await A.js(`document.querySelector('[aria-label="Accumulated rake"]').textContent.includes('₱341')&&document.querySelector('[aria-label="Accumulated rake"]').textContent.includes('140 chips')`));
writeFileSync(OUT+'/rake-extra-results.json',JSON.stringify(results,null,2));if(results.some(r=>!r.ok))process.exitCode=1;
}finally{ws.close();chrome.kill();}
