import {spawn} from 'node:child_process';
import {writeFileSync,mkdirSync,readFileSync} from 'node:fs';
const OUT=process.env.PN_REVIEW_DIR || '/private/tmp/pn-rack-review';mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const chrome=spawn(process.env.PN_CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--remote-debugging-port=9341',`--user-data-dir=/private/tmp/pn-rack-chrome`,'--no-first-run','--disable-gpu','about:blank'],{stdio:'ignore'});
let url;for(let i=0;i<40&&!url;i++){try{url=(await(await fetch('http://127.0.0.1:9341/json/version')).json()).webSocketDebuggerUrl;}catch{await sleep(150)}}
const ws=new WebSocket(url);await new Promise(r=>ws.onopen=r);let id=0;const wait=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(wait.has(m.id)){const [ok,no]=wait.get(m.id);wait.delete(m.id);m.error?no(Error(JSON.stringify(m.error))):ok(m.result)}};
const send=(method,params={},sessionId)=>new Promise((ok,no)=>{wait.set(++id,[ok,no]);ws.send(JSON.stringify({id,method,params,sessionId}))});
async function user(name){const {browserContextId}=await send('Target.createBrowserContext');const{targetId}=await send('Target.createTarget',{url:'about:blank',browserContextId});const{sessionId:s}=await send('Target.attachToTarget',{targetId,flatten:true});await send('Page.enable',{},s);await send('Network.enable',{},s);await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},s);
const js=async expression=>{let r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},s);if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
const go=async path=>{await send('Page.navigate',{url:(process.env.PN_BROWSER_URL || 'http://127.0.0.1:8765')+path},s);await sleep(450);for(let i=0;i<30;i++){if(await js('document.readyState')==='complete')break;await sleep(100)}};
const click=async expr=>{await js(expr+'.click()');await sleep(650)};
const shot=async name=>{await js('window.scrollTo(0,0)');await js('document.fonts.ready');const{cssContentSize:size}=await send('Page.getLayoutMetrics',{},s);const{data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:size.width,height:size.height,scale:1}},s);writeFileSync(`${OUT}/${name}.png`,Buffer.from(data,'base64'))};
await go('/accounts/login/');if(name)await js(`document.querySelector('[name=username]').value=${JSON.stringify(name)};document.querySelector('[name=password]').value='tablestakes-91';document.querySelector('form.form-section button').click()`);await sleep(650);
return {s,js,go,click,shot};}
const results=[];const check=(name,ok)=>{results.push({name,ok});console.log(`${ok?'PASS':'FAIL'} ${name}`)};
const submit=async(U,values,selector='form.form-section[method=post]')=>{await U.js(`const f=document.querySelector(${JSON.stringify(selector)});for(const [k,v] of Object.entries(${JSON.stringify(values)}))f.elements[k].value=v;f.noValidate=true;f.requestSubmit()`);await sleep(700)};
try{const A=await user('hana'),N=await user('');
await N.go('/accounts/signup/?next=/');await submit(N,{username:'new-browser-account',password1:'tablestakes-91',password2:'tablestakes-91'});check('signup succeeds and safe next',await N.js(`location.pathname==='/'&&document.body.textContent.includes('new-browser-account')`));
await submit(N,{name:'New browser group'},'form[action="/g/new/"]');check('group creation succeeds',await N.js(`document.body.textContent.includes('New browser group')&&location.pathname.startsWith('/g/')`));
await N.js(`document.querySelector('form[action$="/tables/new/"]').closest('details').open=true`);await submit(N,{name:'Kitchen',seat_count:'6'},'form[action$="/tables/new/"]');check('table creation succeeds',await N.js(`document.body.textContent.includes('Kitchen')&&document.body.textContent.includes('6 seats')`));
const newPreset=await N.js(`document.querySelector('a[href$="/presets/new/"]').getAttribute('href')`);
for(const unit of ['php','chips']){await N.go(newPreset);await submit(N,{name:'Browser '+unit,game_type:'nlh',unit,small_blind:'10',big_blind:'20',min_buy_in:'500',max_buy_in:'2000',default_buy_in:'1000'});check('preset save '+unit,await N.js(`document.body.textContent.includes('Browser '+${JSON.stringify(unit)})`))}
const create=await N.js(`document.querySelector('a[href$="/sessions/new/"]').getAttribute('href')`);await N.go(create);await submit(N,{game_date:'2026-10-04',location:'Browser kitchen',game_type:'nlh',unit:'chips',small_blind:'10',big_blind:'20',min_buy_in:'500',max_buy_in:'2000',default_buy_in:'1000'});check('new session succeeds',await N.js(`location.pathname.startsWith('/s/')&&document.body.textContent.includes('Chips game')`));
const setPath=await N.js(`location.pathname`);await N.go(setPath+'settings/');await submit(N,{small_blind:'50',big_blind:'20',min_buy_in:'500',max_buy_in:'2000',default_buy_in:'1000'});check('settings service refusal is local and bound',await N.js(`document.querySelector('[name=small_blind]').value==='50'&&document.querySelector('.form-section .errors').textContent.includes('small blind')`));await submit(N,{small_blind:'10',big_blind:'20',min_buy_in:'500',max_buy_in:'2000',default_buy_in:'1000'});check('settings save succeeds',await N.js(`location.pathname===${JSON.stringify(setPath)}`));
await A.go('/g/1/');const rename=await A.js(`document.querySelector('form[action$="/rename/"]').getAttribute('action')`);await A.js(`document.querySelector('form[action$="/rename/"]').closest('details').open=true`);await submit(A,{name:'Ben'},'form[action='+JSON.stringify(rename)+']');check('rename refusal retains name',await A.js(`document.querySelector('form[action='+${JSON.stringify(JSON.stringify(rename))}+'] [name=name]').value==='Ben'&&!!document.querySelector('form[action='+${JSON.stringify(JSON.stringify(rename))}+'] .errors')`));
await submit(A,{name:'Renamed browser player'},'form[action='+JSON.stringify(rename)+']');check('rename succeeds',await A.js(`document.body.textContent.includes('Renamed browser player')`));
await A.go('/s/3/players/add-several/');const selected=await A.js(`const f=document.querySelector('[data-pick]');const free=Number(f.dataset.free);const boxes=[...f.querySelectorAll('[name=member_id]:not(:disabled)')].slice(0,free+1);boxes.forEach(b=>b.checked=true);f.noValidate=true;f.requestSubmit();boxes.length`);await sleep(700);check('picker capacity refusal retains selection',await A.js(`!!document.querySelector('.notice-bad')&&document.querySelectorAll('[name=member_id]:checked').length===${selected}`));
await send('Emulation.setScriptExecutionDisabled',{value:true},A.s);await A.js(`const f=document.querySelector('[data-pick]');[...f.querySelectorAll('[name=member_id]:checked')].slice(1).forEach(b=>b.checked=false);f.requestSubmit()`);await sleep(700);check('native picker succeeds',await A.js(`location.pathname==='/s/3/'&&document.body.textContent.includes('Added 1 player')`));
writeFileSync(`${OUT}/actions.json`,JSON.stringify(results,null,2));}finally{await send('Browser.close');ws.close();chrome.kill()}
if(results.some(x=>!x.ok))process.exitCode=1;
