# Generated by Django 6.1.1 on 2026-10-03 14:38

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=60)),
                ("contact", models.CharField(blank=True, max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[("host", "Host"), ("player", "Player")],
                        default="player",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("removed", "Removed")],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="groups.gamegroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name", "id"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="member_user_status")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("group", "user"),
                        name="member_one_per_user_per_group",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("display_name"),
                        models.F("group"),
                        condition=models.Q(("status", "active")),
                        name="member_active_name_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["host", "player"])),
                        name="member_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "removed"])),
                        name="member_status_valid",
                    ),
                ],
            },
        ),
    ]
