# Generated by Django 6.1.1 on 2026-10-04 06:05

import django.db.models.deletion
from django.db import migrations, models


def create_accounts(apps, schema_editor):
    Group = apps.get_model("groups", "GameGroup")
    Account = apps.get_model("groups", "GroupRakeAccount")
    Account.objects.using(schema_editor.connection.alias).bulk_create(
        Account(group_id=pk) for pk in Group.objects.using(schema_editor.connection.alias).values_list("pk", flat=True)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_invite"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupRakeAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rake_account",
                        to="groups.gamegroup",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_accounts, migrations.RunPython.noop),
    ]
