# Generated by Django 6.1.1 on 2026-10-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0002_invite"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingsPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("small_blind_centavos", models.BigIntegerField()),
                ("big_blind_centavos", models.BigIntegerField()),
                ("min_buy_in_centavos", models.BigIntegerField()),
                ("max_buy_in_centavos", models.BigIntegerField()),
                ("default_buy_in_centavos", models.BigIntegerField()),
                ("chips_per_buy_in", models.BigIntegerField()),
                ("name", models.CharField(max_length=60)),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("nlh", "No-Limit Hold'em"),
                            ("plo", "Pot-Limit Omaha"),
                            ("other", "Other"),
                        ],
                        default="nlh",
                        max_length=8,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presets",
                        to="groups.gamegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("seat_count", models.PositiveSmallIntegerField(default=9)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "default_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="games.settingspreset",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="groups.gamegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="settingspreset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("group", "name"),
                name="preset_active_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingspreset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("big_blind_centavos__gte", models.F("small_blind_centavos")),
                    ("small_blind_centavos__gt", 0),
                ),
                name="preset_blinds_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingspreset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_buy_in_centavos__gte", models.F("min_buy_in_centavos")),
                    ("max_buy_in_centavos__gte", models.F("default_buy_in_centavos")),
                    ("min_buy_in_centavos__gt", 0),
                ),
                name="preset_buy_in_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingspreset",
            constraint=models.CheckConstraint(
                condition=models.Q(("chips_per_buy_in__gt", 0)),
                name="preset_chips_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("group", "name"), name="table_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.CheckConstraint(
                condition=models.Q(("seat_count__gte", 2), ("seat_count__lte", 12)),
                name="table_seat_count_valid",
            ),
        ),
    ]
