# Generated by Django 6.1.1 on 2026-10-03 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("groups", "0002_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("nlh", "No-Limit Hold'em"),
                            ("plo", "Pot-Limit Omaha"),
                            ("other", "Other"),
                        ],
                        default="nlh",
                        max_length=8,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("open", "Open"),
                            ("running", "Running"),
                            ("reconciliation", "Counting chips"),
                            ("finalized", "Finalized"),
                            ("canceled", "Canceled"),
                        ],
                        default="setup",
                        max_length=16,
                    ),
                ),
                ("seat_count", models.PositiveSmallIntegerField()),
                ("rate_centavos", models.BigIntegerField(blank=True, null=True)),
                ("rate_chips", models.BigIntegerField(blank=True, null=True)),
                ("version", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="groups.gamegroup",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="games.table",
                    ),
                ),
            ],
            options={
                "ordering": ["-game_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("joined", "Playing"),
                            ("withdrawn", "Withdrawn"),
                            ("left", "Left"),
                        ],
                        default="joined",
                        max_length=10,
                    ),
                ),
                ("join_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="groups.member",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="games.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "join_order"],
            },
        ),
        migrations.CreateModel(
            name="SettingsVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("small_blind_centavos", models.BigIntegerField()),
                ("big_blind_centavos", models.BigIntegerField()),
                ("min_buy_in_centavos", models.BigIntegerField()),
                ("max_buy_in_centavos", models.BigIntegerField()),
                ("default_buy_in_centavos", models.BigIntegerField()),
                ("chips_per_buy_in", models.BigIntegerField()),
                ("number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="games.settingspreset",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_versions",
                        to="games.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "number"],
            },
        ),
        migrations.AddIndex(
            model_name="gamesession",
            index=models.Index(
                fields=["group", "state", "game_date"], name="session_group_state_date"
            ),
        ),
        migrations.AddIndex(
            model_name="gamesession",
            index=models.Index(
                fields=["table", "game_date"], name="session_table_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamesession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "setup",
                            "open",
                            "running",
                            "reconciliation",
                            "finalized",
                            "canceled",
                        ],
                    )
                ),
                name="session_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="gamesession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("rate_centavos__isnull", True), ("rate_chips__isnull", True)
                    ),
                    models.Q(("rate_centavos__gt", 0), ("rate_chips__gt", 0)),
                    _connector="OR",
                ),
                name="session_rate_both_or_neither",
            ),
        ),
        migrations.AddConstraint(
            model_name="gamesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("seat_count__gte", 2), ("seat_count__lte", 12)),
                name="session_seat_count_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(fields=["member"], name="participant_member"),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("session", "member"), name="participant_once_per_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("session", "join_order"), name="participant_join_order_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["joined", "withdrawn", "left"])),
                name="participant_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsversion",
            constraint=models.UniqueConstraint(
                fields=("session", "number"), name="settings_version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("big_blind_centavos__gte", models.F("small_blind_centavos")),
                    ("small_blind_centavos__gt", 0),
                ),
                name="settings_blinds_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_buy_in_centavos__gte", models.F("min_buy_in_centavos")),
                    ("max_buy_in_centavos__gte", models.F("default_buy_in_centavos")),
                    ("min_buy_in_centavos__gt", 0),
                ),
                name="settings_buy_in_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("chips_per_buy_in__gt", 0)),
                name="settings_chips_positive",
            ),
        ),
    ]
