# Generated by Django 6.1.1 on 2026-10-03 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_units_instead_of_chip_rate"),
        ("groups", "0002_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="state",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("open", "Open"),
                    ("running", "Running"),
                    ("reconciliation", "Counting up"),
                    ("finalized", "Finalized"),
                    ("canceled", "Canceled"),
                ],
                default="setup",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="gamesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit__in", ["php", "chips"])),
                name="session_unit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingspreset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("big_blind__gte", models.F("small_blind")), ("small_blind__gt", 0)
                ),
                name="preset_blinds_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingspreset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_buy_in__gte", models.F("min_buy_in")),
                    ("max_buy_in__gte", models.F("default_buy_in")),
                    ("min_buy_in__gt", 0),
                ),
                name="preset_buy_in_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("big_blind__gte", models.F("small_blind")), ("small_blind__gt", 0)
                ),
                name="settings_blinds_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_buy_in__gte", models.F("min_buy_in")),
                    ("max_buy_in__gte", models.F("default_buy_in")),
                    ("min_buy_in__gt", 0),
                ),
                name="settings_buy_in_range_valid",
            ),
        ),
    ]
