# Generated by Django 6.1.1 on 2026-10-03 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_gamenight"),
        ("groups", "0002_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gamenight",
            index=models.Index(
                fields=["group", "status", "game_date"], name="night_group_status_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamenight",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "closed"])),
                name="night_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="gamesession",
            constraint=models.UniqueConstraint(
                fields=("night", "set_number"), name="set_number_unique_in_night"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["setup", "open", "running"])),
                fields=("night",),
                name="night_one_set_in_play",
            ),
        ),
    ]
