# Generated by Django 6.1.1 on 2026-10-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_gamenight_night_group_status_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PlayInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_intervals",
                        to="games.participant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_intervals",
                        to="games.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at", "id"],
                "indexes": [
                    models.Index(fields=["session"], name="play_interval_session")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("participant",),
                        name="play_interval_one_open",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("ended_at__gte", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="play_interval_ends_after_start",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_periods",
                        to="games.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("session",),
                        name="play_period_one_open",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("ended_at__gte", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="play_period_ends_after_start",
                    ),
                ],
            },
        ),
    ]
