# Generated by Django 6.1.1 on 2026-10-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_backfill_ended_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="start_request_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
