# Generated by Django 6.1.1 on 2026-10-04 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_gamesession_start_request_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsversion",
            name="rake_basis_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="settingsversion",
            name="rake_flat",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="settingsversion",
            name="rake_mode",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("percent", "Percentage"),
                    ("flat", "Flat amount"),
                ],
                default="off",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="settingsversion",
            name="request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="settingsversion",
            constraint=models.UniqueConstraint(
                fields=("session", "request_id"), name="settings_request_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("rake_basis_points", 0), ("rake_flat", 0), ("rake_mode", "off")
                    ),
                    models.Q(
                        ("rake_basis_points__gte", 1),
                        ("rake_basis_points__lte", 9999),
                        ("rake_flat", 0),
                        ("rake_mode", "percent"),
                    ),
                    models.Q(
                        ("rake_basis_points", 0),
                        ("rake_flat__gt", 0),
                        ("rake_mode", "flat"),
                    ),
                    _connector="OR",
                ),
                name="settings_rake_valid",
            ),
        ),
    ]
